CREATE TABLE companies (
    id INT IDENTITY(1,1) PRIMARY KEY,
    company_name NVARCHAR(150) NOT NULL,
    email NVARCHAR(150) NOT NULL UNIQUE,
    password_hash NVARCHAR(255) NOT NULL,
    status NVARCHAR(30) NOT NULL DEFAULT 'PENDING_APPROVAL',
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);